#import "Tinfoil.h"
#import "tinfoil-react-native-Swift.h" // auto-generated Swift-to-ObjC header

@implementation Tinfoil
RCT_EXPORT_MODULE() // mandatory macro

#pragma mark - <NativeTinfoilSpec> methods generated by codegen

- (void)initialize:(NSDictionary *)config {
  [[TinfoilBridge new] initialize:
        config[@"apiKey"]
        githubRepo:config[@"githubRepo"]
        enclaveURL:config[@"enclaveURL"]
        completion:^(NSError * _Nullable err) {
          if (err) {
            NSLog(@"⚠️ Tinfoil initialisation failed: %@", err);
          }
        }];
}

- (void)chatCompletion:(NSString *)model
              messages:(NSArray *)messages
               resolve:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject
{
  [[TinfoilBridge new] chatCompletion:model
                              messages:messages
                            completion:^(NSString * _Nullable text,
                                         NSError  * _Nullable error)
  {
    if (error) {
      reject([NSString stringWithFormat:@"%ld", (long)error.code],
             error.localizedDescription,
             error);
    } else {
      resolve(text ?: @"");
    }
  }];
}

#pragma mark - TurboModule boiler-plate

- (std::shared_ptr<facebook::react::TurboModule>)
    getTurboModule:(const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeTinfoilSpecJSI>(params);
}
@end